// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Chats.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220510080123_try")]
    partial class @try
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Message", b =>
                {
                    b.Property<string>("MessageId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("content")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("fromId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("sent")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("toId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("MessageId");

                    b.HasIndex("fromId");

                    b.HasIndex("toId");

                    b.ToTable("messages");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Property<string>("userId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("nickName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("server")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("userId");

                    b.ToTable("users");
                });

            modelBuilder.Entity("UserMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("fromId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("messageId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("toId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("messageId");

                    b.ToTable("userMessages");
                });

            modelBuilder.Entity("UserUserMessage", b =>
                {
                    b.Property<string>("contactsuserId")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("userMessagesId")
                        .HasColumnType("int");

                    b.HasKey("contactsuserId", "userMessagesId");

                    b.HasIndex("userMessagesId");

                    b.ToTable("UserUserMessage");
                });

            modelBuilder.Entity("Message", b =>
                {
                    b.HasOne("User", "from")
                        .WithMany()
                        .HasForeignKey("fromId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("User", "to")
                        .WithMany()
                        .HasForeignKey("toId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("from");

                    b.Navigation("to");
                });

            modelBuilder.Entity("UserMessage", b =>
                {
                    b.HasOne("Message", "message")
                        .WithMany("userMessages")
                        .HasForeignKey("messageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("message");
                });

            modelBuilder.Entity("UserUserMessage", b =>
                {
                    b.HasOne("User", null)
                        .WithMany()
                        .HasForeignKey("contactsuserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UserMessage", null)
                        .WithMany()
                        .HasForeignKey("userMessagesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Message", b =>
                {
                    b.Navigation("userMessages");
                });
#pragma warning restore 612, 618
        }
    }
}
